### ISSUE TITLE
Error for indels in a small corner case where the chromosome starts with a gene

### ISSUE THREAD

**Issue by Hu-JIN** [AlexandrovLab/SigProfilerMatrixGenerator#117]
Hi,

The `.strip()` in https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/master/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGenerator.py#L748 should be removed. Using `strip()` on binary strings may lead to unwanted behavior. 

I discovered this when generating indel matrices on a chromosome that starts with a gene. As a result, some nucleotides are removed by `strip()` when the binary chromosome string is being read in. I think this is due to a collapse between the binary definition used here and the whitespace as defined in `strip()`. 

SNVs do not suffer from this problem because there is no `.strip()` in https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/master/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGenerator.py#L276.

**Comment by mdbarnesUCSD** [comment]
Hi @Hu-JIN,

Could you please provide an example input that produces this error? Thanks.

**Comment by alertvv** [comment]
Hi,
I am running SigProfilerMatrixGenerator and I found that in the output plots the 'y' axis is not properly labeled.
It is annotated as 0,0,1,1,1, instead of 0,1,2,3,4.
I would really appreciate if it could be fixed in the code, please.
Thank you so much

Por favor, en esta pagina, pon este mensaje, pero que no salga tu nombre ni mi nombre ni nada, porque el autor me ha dicho que para corregir esto hay que escribirlo en github
puedes hacerlo tu por favor. thank you very much

**Comment by mdbarnesUCSD** [comment]
Please reach out if you are able to reproduce this issue.
