### ISSUE TITLE
Specify installation directory for genomes

### ISSUE THREAD

**Issue by stefanoberri** [AlexandrovLab/SigProfilerMatrixGenerator#131]
I was looking at how a genome (fasta file) is installed, but looking the function `install` in this file
https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/c3139c77ee315dc65b5c59b656c410eb440732e5/SigProfilerMatrixGenerator/install.py#L382

It looks like that it is not possible to specify where the genome is installed which defaults the directory where the package is installed:

```python
ref_dir = os.path.dirname(os.path.abspath(__file__))
```

This creates some issues:
- It the package is installed by `root`, a user cannot install separate genome.
- If using a technology such as Docker, it can be problematic to install a genome at runtime, because often the mounted directory there cannot expand.

I would like to contribute a change where it becomes possible to provide explicitly location of the directory. The current behaviour will not be affected. Later, I will provide a similar option for functions using the reference genomes.

Please let me know if I am missing anything, and if I can move forward with a PR

**Comment by mdbarnesUCSD** [comment]
Hi @stefanoberri,

Thanks for reaching out about the installation issue, and for proposing a solution. I think your idea of modifying the installation path sounds good, and I'll be happy to review your pull request when it is ready. Please reach out if you have any questions.

Thanks!

**Comment by stefanoberri** [comment]
Hi @mdbarnesUCSD, I am getting to understand the code more and more as I work on it and change it. I would like to double check with you that my analysis are correct.

- It looks like the installation happens through `SigProfilerMatrixGenerator.install.install` which is referred to in the README and is used by the script `install_genome.py` in the root folder. However, the entrypoint of `SigProfilerMatrixGenerator/install.py` seem to do something different and, from what I can tell, very unlikly to actually work. It is not documented, and when I tried using it, it did not work. Is that correct? Should it be removed?
- I now understand that the "reference" is a mix of files present in this repository under `SigProfilerMatrixGenerator/references` and a fasta file that needs to be "installed". There is high coupling between the fasta file to install and the code, as the files in the repository are made for (or from) the fasta file to download, and that is probably the reason why a checksum is performed. Is that correct? The change suggested for this issue  will then need to change location of the fasta file only.

If there is anything else I seem to have missed or some more info, please let me know.

**Comment by stefanoberri** [comment]
Looking even closer at the code, I realised that the "reference" that gets installed is not the fasta files, but `*.txt` files that go in the `tsb` (transcriptional strand bias, right?) folder, is that correct @mdbarnesUCSD ?

I am a bit confused and have some questions:
- Is this the case for all "references"? I do see that the some code also mentions fasta files. Are they used? what is the difference?
- These files seem compressed files? How do you read them?
- What are the components of the "reference" that get installed? Anything behind fasta and tsb?

Thanks a lot

**Comment by mdbarnesUCSD** [comment]
Thanks @stefanoberri for posting these questions again as I missed them earlier. 

- The entry point of [SigProfilerMatrixGenerator/install.py](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/master/SigProfilerMatrixGenerator/install.py#L1026-L1107) is dated and has now been removed in commit 7e22bf1. 
- Fasta files are used (and later removed) during custom genome installation to create the files in the tsb directory. The files in the tsb directory for the supported genomes are downloaded from the FTP server and then the checksum is performed. My understanding of the tsb files is that each byte in the file encodes information about the base at its corresponding position. The other directories (located under SigProfilerMatrixGenerator/references/chromosomes/) are exome, transcripts, and tsb_BED, and these contain the relevant files for each of the supported genomes. 
-  The directory `references/chromosomes/tsb/` is the only directory affected (tar file downloaded then unzipped) when downloading a supported genome. Custom genome installation affects the following subdirectories of `reference/chromosome/ ` : `exome`, `transcripts`, `tsb`, `tsb_BED`, and `fasta`. The location of where `tsb` files are located and retrieved needs to be modified in order to specify the destination for supported genome installation.

Hope this helped answer your questions.

**Comment by stefanoberri** [comment]
Thank you @mdbarnesUCSD. Very informative indeed. It confirms that `references/chromosomes/tsb/` is what I need to focus on. Thanks a lot.

**Comment by nservant** [comment]
Hi,
Any recent news on this topic ? I'm interested and having the same issue here ;)
Thanks
Nicolas

**Comment by mdbarnesUCSD** [comment]
Thanks @stefanoberri for having worked on this and making progress thus far. I am working on this again, and am aiming to have these updates out in the next few weeks.

**Comment by mdbarnesUCSD** [comment]
Hi, thanks for offering. I am working on an update that will make this feature accessible to the user. Given your bandwidth, I'll push the changes early this week. If you take a look and see anything or have any ideas for tests, let me know!

**Comment by nservant** [comment]
Great ! will you generate a new tag / release soon ? for `pip` install

**Comment by mdbarnesUCSD** [comment]
Yes, v1.2.18 release and tag are now available. Please reach out if you encounter any issues.

**Comment by nservant** [comment]
Test ok. Of note, it seems to work only if we provide an absolute path
```
from SigProfilerMatrixGenerator import install as genInstall
genInstall.install('GRCh37', volume="/data/tmp/")
genInstall.install('GRCh37', volume="./") ## run but I do not see anyfiles in my current folder
```

**Comment by mdbarnesUCSD** [comment]
Thank you for pointing it out. The issue with the current working directory arises because the program changes directories during runtime; we'll investigate this further for non-absolute paths. Additionally, other repositories (like SigProfilerAssignment) will require updates to accommodate these changes.

**Comment by nservant** [comment]
Thanks. Should I open other issues in the other repositories to keep track of it ?
