### ISSUE TITLE
Cannot access references installed to alternative directories in MutationMatrixGenerator.reference_paths function.

### ISSUE THREAD

**Issue by cdupai-bbi** [AlexandrovLab/SigProfilerMatrixGenerator#171]
https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/411e2e83cffb7a6fdb2746cb188fd155f922bf53/SigProfilerMatrixGenerator/scripts/MutationMatrixGenerator.py#L88

In the above function there is no option to supply a path that could be passed to ref_install.reference_dir(). This makes it impossible to access alternative reference directory locations from other SigProfiler modules, e.g. SigProfilerSimulator. We are attempting to run several SigProfiler modules in a singularity container without write access and currently it is impossible to run SigProfilerSimulator with a panel bed file as the script attempts to write the BED reference to 
`/usr/local/lib/python3.9/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh38/BED_GRCh38_proportions.txt` which is read-only.

**Comment by mdbarnesUCSD** [comment]
Hi @cdupai-bbi,

Thanks for reaching out about this. SigProfilerSimulator has not yet been updated to support the "volume" parameter, which is a user defined directory for saving and loading reference genomes and plot templates. We will update this function in a subsequent release so that SigProfilerSimulator may also be containerized.
