### ISSUE TITLE
Bad notion for invalid MAF format

### ISSUE THREAD

**Issue by ShixiangWang** [AlexandrovLab/SigProfilerMatrixGenerator#22]
Dear developer,

Thanks for your nice tool along with SigProfiler and the corresponding important work.

I found the notion `The given input files do not appear to be in the correct MAF format.` is bad for understanding and using this tool. The code does not do what they mean. The `continue` sentence here just skip one row and go to the next line of data, if indeed an invalid MAF provided by a user, an error should be immediately raised for saving the user time and stopping generate the wrong output.

https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/63addbf193d728d78aee1378744820d66dff2397/SigProfilerMatrixGenerator/scripts/convert_input_to_simple_files.py#L1052-L1056

When I installed this package, I also found Pandas is a dependent package, I am curious about why this tool does not use `read_csv()` to handle the input? It may make this tool more compatible, e.g., columns of most MAF files are not ordered as GDC docs describe, they should be handled properly.

Best,
Shixiang

**Comment by ebergstr** [comment]
Hi Shixiang,

Thank you for your feedback. Instead of raising an error, I now immediately break the loop through the file. We have experienced batches of files in a single project where only some of the files are poorly formatted, but wish to classify the remaining files.

We have considered using the read_csv() function, but have not transitioned to this yet.

**Comment by ShixiangWang** [comment]
I understand your consideration, thanks to the reply :).
