### ISSUE TITLE
Question about micro-homology

### ISSUE THREAD

**Issue by taoziyu97** [AlexandrovLab/SigProfilerMatrixGenerator#23]
Dear developer,

Thanks for creating this wonderful tool.

I am reading the source code about how to generate mutational matrix for INDEL.
I have some questions about understanding the processing steps and and their meanings.

- What's the biological significance of the upstream and downstream micro-homology sequence?
- Does the micro-homology sequence affect the mutation events？
- Why do you use both upstream and downstream sequences rather than only the downstream sequence in micro-homology classification? 

Could you help me out?

Best wishes,
Ziyu

**Comment by taoziyu97** [comment]
Can anyone hear me and answer my questions?

Thanks in advance :).

**Comment by ebergstr** [comment]
Hi Ziyu,

Thank you for your questions. The upstream and downstream micro-homology sequence informs us about the length of the overlap between adjacent segments of DNA. Typically, microhomology signatures are indicative of non-homologous end joining pathways. As such, the upstream and downstream sequences help to align the two DNA strands at damaged regions during these more error-prone repair processes.

To answer your second question, I do not believe anyone has considered the sequence context of the homology itself with respect to the biological implications. However, using the matrix generator, you may notice that we have an ID8628 matrix. This file includes a more comprehensive sequence context classification for indels. 
 
Finally, we look for both the upstream and downstream sequences because there may be partial homologies on either end of the insertion and deletion. In the rare case that there are homologies both upstream and downstream of the mutational event, we classify the larger of the two homologies. 

I hope this answers your questions.

Best,
Erik
