### ISSUE TITLE
ID_TSB plots no "Nontranscribed" group like SBS_288

### ISSUE THREAD

**Issue by keiranmraine** [AlexandrovLab/SigProfilerMatrixGenerator#36]
Hi,

Versions:

```
SigProfilerMatrixGenerator==1.1.16
sigProfilerPlotting==1.1.6
```

Not sure if this is a limitation, but the lack of the 3rd group "Nontranscribed" results in a loss of large amounts of data when comparing ID_83 to ID_TSB plots:

## ID_83

![Screen Shot 2020-06-19 at 11 23 08](https://user-images.githubusercontent.com/3740323/85122962-52235900-b21f-11ea-8c91-8960d8e08ee1.png)

## ID_TSB

![Screen Shot 2020-06-19 at 11 23 48](https://user-images.githubusercontent.com/3740323/85123009-623b3880-b21f-11ea-9131-8aa1c142db1f.png)

This isn't an issue on SBS_96 vs SBS_288 as all variants are accounted for.

**Comment by ebergstr** [comment]
You are correct that we are missing out on a great deal of information. The ID-TSB plots were constructed with respect to the old SBS-192 convention (since a large majority of samples that were analyzed were from WES). We are moving towards and exploring the SBS-288 context in greater detail. As such, this will eventually be expanded towards indels as well. Thank you for the feedback.
