### ISSUE TITLE
mm39 analysis requires MT.txt, chr20.txt, 21.txt and 22.txt

### ISSUE THREAD

**Issue by IanCodes** [AlexandrovLab/SigProfilerMatrixGenerator#59]
I think this bug is similar to another issue (https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/issues/42).
Using the installed 'mm39' genome the analysis stalls here:
`Starting matrix generation for INDELs...>>>`

The log mentions that various txt files are missing from '/references/chromosomes/tsb/mm39/', including MT.txt, chr20.txt, 21.txt and 22.txt.

I got round this by adding empty files for those missing above.

**Comment by mdbarnesUCSD** [comment]
Hi @IanCodes,

Could you verify if the bug is similar to (#57)?

If so, I believe this issue was resolved in the 1.1.28 release and you can update your package with:
`pip install --upgrade SigProfilerMatrixGenerator`

If updating the package to newest release does not work, please post the contents of the log files.

Thanks!

**Comment by IanCodes** [comment]
Hi,

I installed SP via pip install, version 1.1.28.

**Comment by mbarnesUCSD** [comment]
Hi @IanCodes,

Could you please provide the log output (.out)? I believe the message above is from the error file.

Thanks!

**Comment by mdbarnesUCSD** [comment]
Hi @IanCodes,

Could you please provide the log output (.out)? I believe the message above is from the error file.

Thanks!

**Comment by mdbarnesUCSD** [comment]
Please reopen this issue if this is something that still needs to be addressed.
