### ISSUE TITLE
Custom CNV Matrix

### ISSUE THREAD

**Issue by hannanw** [AlexandrovLab/SigProfilerMatrixGenerator#71]
Hi,

Thanks for creating such a wonderful and easy to use tool. I was wondering if it is possible to create my own matrix with features other than the predefined ones, maybe I could add on to the features or have a new set entirely. If so, would it then also be possible to extract signatures from it using the accompanying SigProfile Extractor tool? I could not find any option to input a custom matrix there. Any insight or suggestions would be greatly appreciated, thanks!

Warmest regards,
Hannan

**Comment by ebergstr** [comment]
Hi Hannan,

Thank you for the feedback, and we are glad that you find the tool useful! 

Indeed, the extractor can be run using a custom input matrix, whom @marcos-diazg  can provide additional information.

Best,
Erik

**Comment by marcos-diazg** [comment]
Hi Hannan,

Thanks again for your interest in our SigProfiler suite of tools! As Erik mentioned, SigProfilerExtractor can be run using a custom-defined input mutational matrix. Just make sure to follow the same format as for the default context in SigProfilerMatrixGenerator (as many rows as features, as many columns as samples, first row for sample names, first column for feature names).

When running SigProfilerExtractor please use the parameters `input_type='matrix'` and `context_type="number_of_features"` (e.g. if you want to use a matrix of 1,000 features `context_type='1000'`). Also, just a quick reminder that you will no longer have specific plots from SigProfilerPlotting or COSMIC decompositions, since they don't make sense anymore for a custom set of features.

Hope this helps and please let us know if you have further questions.

Best wishes,

Marcos

**Comment by hannanw** [comment]
Hi Marcos and Erik,

Thanks for your replies and additional information, it has been very helpful. I will give it a try with a custom matrix and see what the output looks like. 

Warmest regards,
Hannan
